CREATE TABLE person (
	id UUID NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE attachment (
	id UUID NOT NULL PRIMARY KEY,
	filename VARCHAR(100) NOT NULL,
	filetype VARCHAR(100) NOT NULL,
	data BYTEA 
);